### ISSUE TITLE
Error while starting server --> node needs to be resynced

### ISSUE THREAD

**Issue by Kronatore** [deso-protocol/run#99]
Dear all,

I just recently started installing a Deso node. While downloading the chain following error pops up. 

backend   | I1010 10:07:48.781059       1 snapshot.go:2253] EncoderMigration: finished updating prefixes ([[5] [7] [8] [10] [11] [12]])
backend   | I1010 10:07:48.781376       1 snapshot.go:2256] EncoderMigration: currently updating prefix: ([17])
backend   | I1010 10:07:48.781422       1 snapshot.go:2259] Remaining prefixes ([[18] [19] [20] [21] [22] [23] [25] [26] [27] [28] [29] [30] [31] [32] [33] [34] [35] [36] [37] [39] [40] [41] [43] [44] [45] [46] [47] [48] [49] [50] [51] [52] [53] [54] [55] [56] [57] [58] [59] [60] [61] [62]])
backend   | I1010 10:08:42.696402       1 snapshot.go:2295] Finished computing the migration
backend   | I1010 10:08:42.704009       1 node.go:231] Start: Got en error while starting server and shouldRestart is true. Node will be erased and resynced. Error: (NewServer: Problem in ForceResetToLastSnapshot: ForceRestartToLastSnapshot: Snapshot epoch checksum: ([0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]), and verification checksum: ([72 251 235 78 19 13 50 77 251 195 65 45 205 38 119 56 147 50 119 163 86 18 207 20 222 83 130 244 51 75 229 98]), are not equal. This means recovery failed. Unfortunatelly, we have to resync your node.)
backend   | panic: Node.listenToNodeMessages: Node is currently not running, nodeMessageChan should've not been called!
backend   | 
backend   | goroutine 14 [running]:
backend   | github.com/deso-protocol/core/cmd.(*Node).listenToNodeMessages(0xc000594fc0, {0x0, 0x0, 0x0})
backend   | 	/deso/src/core/cmd/node.go:357 +0x37e
backend   | created by github.com/deso-protocol/core/cmd.(*Node).Start
backend   | 	/deso/src/core/cmd/node.go:78 +0x2ea
backend exited with code 2

Any suggestions what might be the problem?

**Comment by staking-hub** [comment]
I have the same problem. Did you manage to solve it?

**Comment by osontungo** [comment]
me too
